#This is the default settings for the plugin. Please check these settings are what you want BEFORE enabling the plugin.

#MYSQL
#Please change these from the defaults to your mySQL settings.
#You must change mySQL-enabled to true to use your database, otherwise the plugin will operate on config files by default.
#Do not enable and then disable mySQL as it may break your server data.
mySQL:
  mySQL-enabled: false
  host: host
  port: 3306
  database: database
  username: username
  password: password
  minimumConnections: 5
  maximumConnections: 10
  connectionTimeOut: 5000
  
#RANKS
#This is the default rank that all players will have upon joining.
default-rank: Recruit
#This is where you can set the prefix for the default rank.
  prefix: "&f[&aRecruit&f]"
#The default rank is automatically given the following permissions, which you can change.
  permissions:
    kazanjima.*: true
  
#HOMES
#This determines the default amount of homes available to players.
default-max-homes: 2

#PARTIES
party:
#This is the default identifier for party chat.
  prefix: @
#This lets you change the color of the party chat system.
  color-1: WHITE
  color-2: GREEN

